################################################################################
#                                                                              #
# Prediction of Drug Consumption Based on Five Factor Personality Features     #
#                                                                              #
# Author: Eric Gabriel                                                         #
# Date: January 5th, 2021                                                      #
#                                                                              #
# This R script is part of the second project submission of the course         #
# HarvardX PH125.9x "Data Science: Capstone".                                  #
#                                                                              #
# The data set file was already downloaded from <https://archive.ics.uci.edu/  #
# ml/machine-learning-databases/00373/drug_consumption.data> on December 22nd, #
# 2020, and was saved to the "data" sub-directory.                             #
#                                                                              #
# This script loads the downloaded CSV data file and performs cleaning and     #
# pre-processing of the data. Additionally, a data frame for exploring the     #
# correlation of user/non-user groups per drug is created.                     #
#                                                                              #
# After an exploratory data analysis (EDA), three drugs are chosen for         #
# evaluation based on the minimum difference between the amount of users and   #
# non-users: Benzodiazepines, Legal Highs and Ecstasy.                         #
#                                                                              #
# For each of these drugs, four types of models for binary classification into #
# users and non-users are created using a 10-fold cross-validation:            #
# - Boosted Generalized Linear Models (Boosted GLM)                            #
# - k-Nearest-Neighbor Classification (kNN)                                    #
# - Random Forest (RF)                                                         #
# - Regularized Discrimininant Analysis (RDA)                                  #
#                                                                              #
# For each of the evaluated drugs, the results are reported and compared to    #
# the published results of (Fehrman et al. 2015) and (Mahyoub et al. 2019).    #
#                                                                              #
# Finally, the impact of additional input features on the classification       #
# performance is evaluated using user information of the two most correlated   #
# drugs.                                                                       #
#                                                                              #
# The corresponding PDF report contains further details about the data set,    #
# the analysis procedure, the model theories and the results.                  #
# The report can be generated by knitting the Rmd file.                        #
#                                                                              #
################################################################################

# Install libraries if they are not already installed
if(!require(tidyverse)) install.packages("tidyverse")
if(!require(caret)) install.packages("caret")
if(!require(knitr)) install.packages("knitr")
if(!require(corrplot)) install.packages("corrplot")
if(!require(plyr)) install.packages("plyr")
if(!require(mboost)) install.packages("mboost")
if(!require(randomForest)) install.packages("randomForest")
if(!require(klaR)) install.packages("klaR")

# Import libraries

# General
library(tidyverse) 
library(caret)
library(knitr)
library(corrplot)

# Boosted GLM
library(plyr)
library(mboost)

# Random Forest
library(randomForest)

# RDA
library(klaR)

################################################################################

# Set filename to downloaded data set file in CSV format
filename <- file.path("data/drug_consumption.data")

# Read raw CSV data set
data <- read_csv(filename, col_names = F)

# Convert user recency ("CL0" - "CL6") for all drugs (columns X14:X32)
# into a numeric representation
data_clean <- data %>%
  mutate(X14 = as.numeric(str_replace(X14, "CL", "")),
         X15 = as.numeric(str_replace(X15, "CL", "")),
         X16 = as.numeric(str_replace(X16, "CL", "")),
         X17 = as.numeric(str_replace(X17, "CL", "")),
         X18 = as.numeric(str_replace(X18, "CL", "")),
         X19 = as.numeric(str_replace(X19, "CL", "")),
         X20 = as.numeric(str_replace(X20, "CL", "")),
         X21 = as.numeric(str_replace(X21, "CL", "")),
         X22 = as.numeric(str_replace(X22, "CL", "")),
         X23 = as.numeric(str_replace(X23, "CL", "")),
         X24 = as.numeric(str_replace(X24, "CL", "")),
         X25 = as.numeric(str_replace(X25, "CL", "")),
         X26 = as.numeric(str_replace(X26, "CL", "")),
         X27 = as.numeric(str_replace(X27, "CL", "")),
         X28 = as.numeric(str_replace(X28, "CL", "")),
         X29 = as.numeric(str_replace(X29, "CL", "")),
         X30 = as.numeric(str_replace(X30, "CL", "")),
         X31 = as.numeric(str_replace(X31, "CL", "")),
         X32 = as.numeric(str_replace(X32, "CL", ""))) 

# Set column names as provided by the authors:
# https://archive.ics.uci.edu/ml/datasets/Drug+consumption+%28quantified%29#
# (last retrieved: January 5th, 2021)
colnames(data_clean) <- c("ID", "Age", "Gender", "Education", "Country", 
                          "Ethnicity", "NScore", "EScore", "OScore", "AScore",
                          "CScore", "Impulsiveness", "SensationSeeking",
                          "Alcohol", "Amphetamine", "AmylNitrite", "Benzos",
                          "Caffeine", "Cannabis", "Chocolate", "Cocaine",
                          "Crack", "Ecstasy", "Heroine", "Ketamine",
                          "LegalHighs", "LSD", "Meth", "MMushrooms", "Nicotine",
                          "Semeron", "VSA")

# Add 19 columns containing binary user labels for all participants and all
# drugs using the factors "yes" (Recency > 1) and "no" (otherwise)
data_clean <- data_clean %>%
  mutate(Alcohol_User = as.factor(ifelse(Alcohol > 1, "yes", "no")), 
         Amphetamine_User = as.factor(ifelse(Amphetamine > 1, "yes", "no")), 
         AmylNitrite_User = as.factor(ifelse(AmylNitrite > 1, "yes", "no")),
         Benzos_User = as.factor(ifelse(Benzos > 1, "yes", "no")),
         Caffeine_User = as.factor(ifelse(Caffeine > 1, "yes", "no")), 
         Cannabis_User = as.factor(ifelse(Cannabis > 1, "yes", "no")), 
         Chocolate_User = as.factor(ifelse(Chocolate > 1, "yes", "no")), 
         Cocaine_User = as.factor(ifelse(Cocaine > 1, "yes", "no")), 
         Crack_User = as.factor(ifelse(Crack > 1, "yes", "no")), 
         Ecstasy_User = as.factor(ifelse(Ecstasy > 1, "yes", "no")), 
         Heroine_User = as.factor(ifelse(Heroine > 1, "yes", "no")), 
         Ketamine_User = as.factor(ifelse(Ketamine > 1, "yes", "no")), 
         LegalHighs_User = as.factor(ifelse(LegalHighs > 1, "yes", "no")), 
         LSD_User = as.factor(ifelse(LSD > 1, "yes", "no")), 
         Meth_User = as.factor(ifelse(Meth > 1, "yes", "no")), 
         MMushrooms_User = as.factor(ifelse(MMushrooms > 1, "yes", "no")),
         Nicotine_User = as.factor(ifelse(Nicotine > 1, "yes", "no")),
         Semeron_User = as.factor(ifelse(Semeron > 1, "yes", "no")), 
         VSA_User = as.factor(ifelse(VSA > 1, "yes", "no")))

# Evaluate if NA values are present
colSums(is.na(data_clean))

# In a separate data frame, select user data only and convert factor to numeric
# representation such that the amount of users and non-users per drug as well as
# the correlation can be computed
users_data <- data_clean %>%
  mutate(Alcohol_User = ifelse(Alcohol > 1, 1, 0), 
         Amphetamine_User = ifelse(Amphetamine > 1, 1, 0), 
         AmylNitrite_User = ifelse(AmylNitrite > 1, 1, 0),
         Benzos_User = ifelse(Benzos > 1, 1, 0),
         Caffeine_User = ifelse(Caffeine > 1, 1, 0), 
         Cannabis_User = ifelse(Cannabis > 1, 1, 0), 
         Chocolate_User = ifelse(Chocolate > 1, 1, 0), 
         Cocaine_User = ifelse(Cocaine > 1, 1, 0), 
         Crack_User = ifelse(Crack > 1, 1, 0), 
         Ecstasy_User = ifelse(Ecstasy > 1, 1, 0), 
         Heroine_User = ifelse(Heroine > 1, 1, 0), 
         Ketamine_User = ifelse(Ketamine > 1, 1, 0), 
         LegalHighs_User = ifelse(LegalHighs > 1, 1, 0), 
         LSD_User = ifelse(LSD > 1, 1, 0), 
         Meth_User = ifelse(Meth > 1, 1, 0), 
         MMushrooms_User = ifelse(MMushrooms > 1, 1, 0),
         Nicotine_User = ifelse(Nicotine > 1, 1, 0),
         Semeron_User = ifelse(Semeron > 1, 1, 0), 
         VSA_User = ifelse(VSA > 1, 1, 0)) %>%
  dplyr::select(Alcohol_User, Amphetamine_User, AmylNitrite_User, Benzos_User,
                Caffeine_User, Cannabis_User, Chocolate_User, Cocaine_User, 
                Crack_User, Ecstasy_User, Heroine_User, Ketamine_User, 
                LegalHighs_User, LSD_User, Meth_User, MMushrooms_User, 
                Nicotine_User, Semeron_User, VSA_User)

# Compute differences between the amount of users and non-users per drug and
# display drugs with least differences
# The three drugs with least differences will be selected for evaluation
data.frame(yes = colSums(users_data), no = 1885 - colSums(users_data), 
           drug = colnames(users_data)) %>%
  summarise(diff = abs(yes - no), drug = drug) %>%
  arrange(diff) %>%
  head()

# Selected drugs: Benzodiazepines, LegalHighs, Ecstasy

################################################################################
#                                                                              #
# EVALUATION SETUP                                                             #
#                                                                              #
################################################################################

# Create trainControl object for performing a 10-fold cross-validation with a
# training/test-split of 90%/10%. The final predictions shall be saved
# including class probabilities.

cv_10 <- trainControl(
  method = "cv", 
  number = 10,     
  p = 0.9,
  savePredictions = "final",        
  classProbs = TRUE)

################################################################################
#                                                                              #
# BENZODIAZEPINES                                                              #
#                                                                              #
# First, we have chosen the four most discriminative features for users and    #
# non-users of Benzodiazepines by means of largest median difference.          #
# These features will be visualized as boxplots. For the sake of brevity, we   #
# have removed the code for plotting the other features.                       #
#                                                                              #
# We then train four model types for binary classification of users and non-   #
# users: Boosted GLM, kNN, Random Forest and RDA (see report for details).     #
#                                                                              #
################################################################################

# Plot N-Score (Neuroticism) for users and non-users of Benzodiazepines as
# boxplots along with the respective data points and save plot as variable 
# "benzo_plot1". This plot will be used in the report.
benzo_plot1 <- data_clean %>%
  ggplot(aes(Benzos_User, NScore)) + 
  geom_boxplot() + 
  geom_jitter(width = 0.1, alpha = 0.1)

# Plot O-Score (Openness for Experience) for users and non-users of
# Benzodiazepines as boxplots along with the respective data points and save
# plot as variable "benzo_plot2". This plot will be used in the report.
benzo_plot2 <- data_clean %>%
  ggplot(aes(Benzos_User, OScore)) + 
  geom_boxplot() + 
  geom_jitter(width = 0.1, alpha = 0.1)

# Plot Impulsiveness for users and non-users of Benzodiazepines as
# boxplots along with the respective data points and save plot as variable 
# "benzo_plot3". This plot will be used in the report.
benzo_plot3 <- data_clean %>%
  ggplot(aes(Benzos_User, Impulsiveness)) + 
  geom_boxplot() + 
  geom_jitter(width = 0.1, alpha = 0.1)

# Plot Sensation-Seeking for users and non-users of Benzodiazepines as
# boxplots along with the respective data points and save plot as variable 
# "benzo_plot4". This plot will be used in the report.
benzo_plot4 <- data_clean %>%
  ggplot(aes(Benzos_User, SensationSeeking)) + 
  geom_boxplot() + 
  geom_jitter(width = 0.1, alpha = 0.1)

# Create a data frame for storing the Benzodiazepine results of the four
# evaluation metrics (see report). This data frame will later be rendered as
# a table.
benzo_results <- data.frame("Model" = character(),
                            "Sensitivity" = double(),
                            "Specificity" = double(),
                            "Accuracy" = double(), 
                            "Balanced Accuracy" = double(),
                            "Evaluation Method" = character())

# Set seed to 2021 for training the Boosted GLM model
set.seed(2021, sample.kind = "Rounding")
# Train Boosted GLM model for binary classification of users and non-users of
# Benzodiazepines using ten input features (see report) and 10-fold CV
benzo_glm <- train(Benzos_User ~ Age + Gender + Education + NScore + EScore + 
                   OScore + AScore + CScore + Impulsiveness + SensationSeeking,
                   data = data_clean, method = "glmboost", trControl = cv_10)

# Save confusion matrix of final model classification and actual class
confmat_benzo_glm <- confusionMatrix(benzo_glm$pred$pred,
                                     benzo_glm$pred$obs,
                                     positive = "yes")
# Save Boosted GLM results as new row in the result table
benzo_results <- benzo_results %>%
  add_row(Model = "Boosted GLM",
          Sensitivity = confmat_benzo_glm$byClass["Sensitivity"],
          Specificity = confmat_benzo_glm$byClass["Specificity"],
          Accuracy = confmat_benzo_glm$overall["Accuracy"],
          Balanced.Accuracy = confmat_benzo_glm$byClass["Balanced Accuracy"],
          Evaluation.Method = "10-fold CV")

# Set seed to 2021 for training the kNN model
set.seed(2021, sample.kind = "Rounding")
# Train kNN model for binary classification of users and non-users of
# Benzodiazepines using ten input features (see report) and 10-fold CV
benzo_knn <- train(Benzos_User ~ Age + Gender + Education + NScore + EScore + 
                   OScore + AScore + CScore + Impulsiveness + SensationSeeking, 
                   data = data_clean, method = "knn", trControl = cv_10)

# Save confusion matrix of final model classification and actual class
confmat_benzo_knn <- confusionMatrix(benzo_knn$pred$pred,
                                     benzo_knn$pred$obs,
                                     positive = "yes")

# Save kNN results as new row in the result table
benzo_results <- benzo_results %>%
  add_row(Model = "kNN",
          Sensitivity = confmat_benzo_knn$byClass["Sensitivity"],
          Specificity = confmat_benzo_knn$byClass["Specificity"],
          Accuracy = confmat_benzo_knn$overall["Accuracy"],
          Balanced.Accuracy = confmat_benzo_knn$byClass["Balanced Accuracy"],
          Evaluation.Method = "10-fold CV")

# Set seed to 2021 for training the Random Forest model
set.seed(2021, sample.kind = "Rounding")
# Train Random Forest model for binary classification of users and non-users of
# Benzodiazepines using ten input features (see report) and 10-fold CV
benzo_rf <- train(Benzos_User ~ Age + Gender + Education + NScore + EScore + 
                    OScore + AScore + CScore + Impulsiveness + SensationSeeking,
                  data = data_clean, method = "rf", trControl = cv_10)
# Save confusion matrix of final model classification and actual class
confmat_benzo_rf <- confusionMatrix(benzo_rf$pred$pred,
                                    benzo_rf$pred$obs,
                                    positive = "yes")

# Save Random Forest results as new row in the result table
benzo_results <- benzo_results %>%
  add_row(Model = "Random Forest",
          Sensitivity = confmat_benzo_rf$byClass["Sensitivity"],
          Specificity = confmat_benzo_rf$byClass["Specificity"],
          Accuracy = confmat_benzo_rf$overall["Accuracy"],
          Balanced.Accuracy = confmat_benzo_rf$byClass["Balanced Accuracy"],
          Evaluation.Method = "10-fold CV")

# Set seed to 2021 for training the RDA model
set.seed(2021, sample.kind = "Rounding")
# Train RDA model for binary classification of users and non-users of
# Benzodiazepines using ten input features (see report) and 10-fold CV
benzo_rda <- train(Benzos_User ~ Age + Gender + Education + NScore + EScore + 
                   OScore + AScore + CScore + Impulsiveness + SensationSeeking, 
                   data = data_clean, method = "rda", trControl = cv_10)
# Save confusion matrix of final model classification and actual class
confmat_benzo_rda <- confusionMatrix(benzo_rda$pred$pred,
                                     benzo_rda$pred$obs,
                                     positive = "yes")

# Save RDA results as new row in the result table
benzo_results <- benzo_results %>%
  add_row(Model = "RDA",
          Sensitivity = confmat_benzo_rda$byClass["Sensitivity"],
          Specificity = confmat_benzo_rda$byClass["Specificity"],
          Accuracy = confmat_benzo_rda$overall["Accuracy"],
          Balanced.Accuracy = confmat_benzo_rda$byClass["Balanced Accuracy"],
          Evaluation.Method = "10-fold CV")

# Save Benzodiazepine decision tree results of Mahyoub et al. 2019 for 
# comparison as new row in the result table
benzo_results <- benzo_results %>%
  add_row(Model = "Mahyoub et al. DT",
          Sensitivity = 0.416,
          Specificity = 0.649,
          Accuracy = 0.6287,
          Balanced.Accuracy = 0.5325,
          Evaluation.Method = "10-fold CV")

# Save Benzodiazepine kNN results of Mahyoub et al. 2019 for comparison as 
# new row in the result table
benzo_results <- benzo_results %>%
  add_row(Model = "Mahyoub et al. kNN",
          Sensitivity = 0.469,
          Specificity = 0.773,
          Accuracy = 0.6695,
          Balanced.Accuracy = 0.621,
          Evaluation.Method = "10-fold CV")

# Save Benzodiazepine Random Forest results of Mahyoub et al. 2019 for 
# comparison as new row in the result table
benzo_results <- benzo_results %>%
  add_row(Model = "Mahyoub et al. RF",
          Sensitivity = 0.521,
          Specificity = 0.749,
          Accuracy = 0.6747,
          Balanced.Accuracy = 0.635,
          Evaluation.Method = "10-fold CV")

# Save Benzodiazepine decision tree results of Fehrman et al. 2015 for
# comparison as new row in the result table
benzo_results <- benzo_results %>%
  add_row(Model = "Fehrman et al. DT",
          Sensitivity = 0.7087,
          Specificity = 0.7151,
          Accuracy = NA,
          Balanced.Accuracy = 0.7119,
          Evaluation.Method = "LOOCV")

# Render result table for Benzodiazepines to the console
knitr::kable(benzo_results, digits = 3)

################################################################################
#                                                                              #
# LEGAL HIGHS                                                                  #
#                                                                              #
# First, we have chosen the four most discriminative features for users and    #
# non-users of Legal Highs by means of largest median difference.              #
# These features will be visualized as boxplots. For the sake of brevity, we   #
# have removed the code for plotting the other features.                       #
#                                                                              #
# We then train four model types for binary classification of users and non-   #
# users: Boosted GLM, kNN, Random Forest and RDA (see report for details).     #
#                                                                              #
################################################################################

# Plot Age for users and non-users of Legal Highs as
# boxplots along with the respective data points and save plot as variable 
# "lh_plot1". This plot will be used in the report.
lh_plot1 <- data_clean %>%
  ggplot(aes(LegalHighs_User, Age)) + 
  geom_boxplot() + 
  geom_jitter(width = 0.1, alpha = 0.1)

# Plot Education for users and non-users of Legal Highs as
# boxplots along with the respective data points and save plot as variable 
# "lh_plot2". This plot will be used in the report.
lh_plot2 <- data_clean %>%
  ggplot(aes(LegalHighs_User, Education)) + 
  geom_boxplot() + 
  geom_jitter(width = 0.1, alpha = 0.1)

# Plot O-Score (Openness for Experience) for users and non-users of Legal Highs
# as boxplots along with the respective data points and save plot as variable 
# "lh_plot3". This plot will be used in the report.
lh_plot3 <- data_clean %>%
  ggplot(aes(LegalHighs_User, OScore)) + 
  geom_boxplot() + 
  geom_jitter(width = 0.1, alpha = 0.1)

# Plot Sensation-Seeking for users and non-users of Legal Highs as
# boxplots along with the respective data points and save plot as variable 
# "lh_plot4". This plot will be used in the report.
lh_plot4 <- data_clean %>%
  ggplot(aes(LegalHighs_User, SensationSeeking)) + 
  geom_boxplot() + 
  geom_jitter(width = 0.1, alpha = 0.1)

# Create a data frame for storing the Legal Highs results of the four
# evaluation metrics (see report). This data frame will later be rendered as
# a table.
lhigh_results <- data.frame("Model" = character(),
                            "Sensitivity" = double(),
                            "Specificity" = double(),
                            "Accuracy" = double(), 
                            "Balanced Accuracy" = double(),
                            "Evaluation Method" = character())

# Set seed to 2021 for training the Boosted GLM model
set.seed(2021, sample.kind = "Rounding")
# Train Boosted GLM model for binary classification of users and non-users of
# Legal Highs using ten input features (see report) and 10-fold CV
lhigh_glm <- train(LegalHighs_User ~ Age + Gender + Education + NScore + EScore + 
                   OScore + AScore + CScore + Impulsiveness + SensationSeeking,
                   data = data_clean, method = "glmboost", trControl = cv_10)
# Save confusion matrix of final model classification and actual class
confmat_lh_glm <- confusionMatrix(lhigh_glm$pred$pred,
                                  lhigh_glm$pred$obs,
                                  positive = "yes")

# Save Boosted GLM results as new row in the result table
lhigh_results <- lhigh_results %>%
  add_row(Model = "Boosted GLM",
          Sensitivity = confmat_lh_glm$byClass["Sensitivity"],
          Specificity = confmat_lh_glm$byClass["Specificity"], 
          Accuracy = confmat_lh_glm$overall["Accuracy"],
          Balanced.Accuracy = confmat_lh_glm$byClass["Balanced Accuracy"],
          Evaluation.Method = "10-fold CV")

# Set seed to 2021 for training the kNN model
set.seed(2021, sample.kind = "Rounding")
# Train kNN model for binary classification of users and non-users of
# Legal Highs using ten input features (see report) and 10-fold CV
lhigh_knn <- train(LegalHighs_User ~ Age + Gender + Education + NScore + EScore + 
                   OScore + AScore + CScore + Impulsiveness + SensationSeeking, 
                   data = data_clean, method = "knn", trControl = cv_10)
# Save confusion matrix of final model classification and actual class
confmat_lh_knn <- confusionMatrix(lhigh_knn$pred$pred,
                                  lhigh_knn$pred$obs,
                                  positive = "yes")

# Save kNN results as new row in the result table
lhigh_results <- lhigh_results %>%
  add_row(Model = "kNN",
          Sensitivity = confmat_lh_knn$byClass["Sensitivity"],
          Specificity = confmat_lh_knn$byClass["Specificity"], 
          Accuracy = confmat_lh_knn$overall["Accuracy"],
          Balanced.Accuracy = confmat_lh_knn$byClass["Balanced Accuracy"],
          Evaluation.Method = "10-fold CV")

# Set seed to 2021 for training the Random Forest model
set.seed(2021, sample.kind = "Rounding")
# Train Random Forest model for binary classification of users and non-users of
# Legal Highs using ten input features (see report) and 10-fold CV
lhigh_rf <- train(LegalHighs_User ~ Age + Gender + Education + NScore + EScore + 
                    OScore + AScore + CScore + Impulsiveness + SensationSeeking,
                  data = data_clean, method = "rf", trControl = cv_10)
# Save confusion matrix of final model classification and actual class
confmat_lh_rf <- confusionMatrix(lhigh_rf$pred$pred,
                                 lhigh_rf$pred$obs,
                                 positive = "yes")

# Save Random Forest results as new row in the result table
lhigh_results <- lhigh_results %>%
  add_row(Model = "Random Forest",
          Sensitivity = confmat_lh_rf$byClass["Sensitivity"],
          Specificity = confmat_lh_rf$byClass["Specificity"], 
          Accuracy = confmat_lh_rf$overall["Accuracy"],
          Balanced.Accuracy = confmat_lh_rf$byClass["Balanced Accuracy"],
          Evaluation.Method = "10-fold CV")

# Set seed to 2021 for training the RDA model
set.seed(2021, sample.kind = "Rounding")
# Train RDA model for binary classification of users and non-users of
# Legal Highs using ten input features (see report) and 10-fold CV
lhigh_rda <- train(LegalHighs_User ~ Age + Gender + Education + NScore + EScore + 
                   OScore + AScore + CScore + Impulsiveness + SensationSeeking, 
                   data = data_clean, method = "rda", trControl = cv_10)
# Save confusion matrix of final model classification and actual class
confmat_lh_rda <- confusionMatrix(lhigh_rda$pred$pred,
                                  lhigh_rda$pred$obs,
                                  positive = "yes")

# Save RDA results as new row in the result table
lhigh_results <- lhigh_results %>%
  add_row(Model = "RDA",
          Sensitivity = confmat_lh_rda$byClass["Sensitivity"],
          Specificity = confmat_lh_rda$byClass["Specificity"], 
          Accuracy = confmat_lh_rda$overall["Accuracy"],
          Balanced.Accuracy = confmat_lh_rda$byClass["Balanced Accuracy"],
          Evaluation.Method = "10-fold CV")

# Save Legal Highs decision tree results of Mahyoub et al. 2019 for 
# comparison as new row in the result table
lhigh_results <- lhigh_results %>%
  add_row(Model = "Mahyoub et al. DT",
          Sensitivity = 0.576,
          Specificity = 0.711, 
          Accuracy = 0.705,
          Balanced.Accuracy = 0.6435,
          Evaluation.Method = "10-fold CV")

# Save Legal Highs kNN results of Mahyoub et al. 2019 for 
# comparison as new row in the result table
lhigh_results <- lhigh_results %>%
  add_row(Model = "Mahyoub et al. kNN",
          Sensitivity = 0.649,
          Specificity = 0.803, 
          Accuracy = 0.7645,
          Balanced.Accuracy = 0.726,
          Evaluation.Method = "10-fold CV")

# Save Legal Highs Random Forest results of Mahyoub et al. 2019 for 
# comparison as new row in the result table
lhigh_results <- lhigh_results %>%
  add_row(Model = "Mahyoub et al. RF",
          Sensitivity = 0.581,
          Specificity = 0.747, 
          Accuracy = 0.756,
          Balanced.Accuracy = 0.664,
          Evaluation.Method = "10-fold CV")

# Save Legal Highs decision tree results of Fehrman et al. 2015 for
# comparison as new row in the result table
lhigh_results <- lhigh_results %>%
  add_row(Model = "Fehrman et al. DT",
          Sensitivity = 0.7953,
          Specificity = 0.8237, 
          Accuracy = NA,
          Balanced.Accuracy = 0.8095,
          Evaluation.Method = "LOOCV")

# Render result table for Legal Highs to the console
knitr::kable(lhigh_results)

################################################################################
#                                                                              #
# ECSTASY                                                                      #
#                                                                              #
# First, we have chosen the four most discriminative features for users and    #
# non-users of Ecstasy by means of largest median difference.                  #
# These features will be visualized as boxplots. For the sake of brevity, we   #
# have removed the code for plotting the other features.                       #
#                                                                              #
# We then train four model types for binary classification of users and non-   #
# users: Boosted GLM, kNN, Random Forest and RDA (see report for details).     #
#                                                                              #
################################################################################

# Plot Age for users and non-users of Ecstasy as
# boxplots along with the respective data points and save plot as variable 
# "ecsta_plot1". This plot will be used in the report.
ecsta_plot1 <- data_clean %>%
  ggplot(aes(Ecstasy_User, Age)) + 
  geom_boxplot() + 
  geom_jitter(width = 0.1, alpha = 0.1)

# Plot Education for users and non-users of Ecstasy as
# boxplots along with the respective data points and save plot as variable 
# "ecsta_plot2". This plot will be used in the report.
ecsta_plot2 <- data_clean %>%
  ggplot(aes(Ecstasy_User, Education)) + 
  geom_boxplot() + 
  geom_jitter(width = 0.1, alpha = 0.1)

# Plot O-Score (Openness for Experience) for users and non-users of Ecstasy as
# boxplots along with the respective data points and save plot as variable 
# "ecsta_plot3". This plot will be used in the report.
ecsta_plot3 <- data_clean %>%
  ggplot(aes(Ecstasy_User, OScore)) + 
  geom_boxplot() + 
  geom_jitter(width = 0.1, alpha = 0.1)

# Plot Sensation-Seeking for users and non-users of Ecstasy as
# boxplots along with the respective data points and save plot as variable 
# "ecsta_plot4". This plot will be used in the report.
ecsta_plot4 <- data_clean %>%
  ggplot(aes(Ecstasy_User, SensationSeeking)) + 
  geom_boxplot() + 
  geom_jitter(width = 0.1, alpha = 0.1)

# Create a data frame for storing the Ecstasy results of the four evaluation
# metrics (see report). This data frame will later be rendered as a table.
ecsta_results <- data.frame("Model" = character(),
                            "Sensitivity" = double(),
                            "Specificity" = double(),
                            "Accuracy" = double(), 
                            "Balanced Accuracy" = double(),
                            "Evaluation Method" = character())

# Set seed to 2021 for training the Boosted GLM model
set.seed(2021, sample.kind = "Rounding")
# Train Boosted GLM model for binary classification of users and non-users of
# Ecstasy using ten input features (see report) and 10-fold CV
ecsta_glm <- train(Ecstasy_User ~ Age + Gender + Education + NScore + EScore + 
                   OScore + AScore + CScore + Impulsiveness + SensationSeeking,
                   data = data_clean, method = "glmboost", trControl = cv_10)
# Save confusion matrix of final model classification and actual class
confmat_ecsta_glm <- confusionMatrix(ecsta_glm$pred$pred,
                                     ecsta_glm$pred$obs,
                                     positive = "yes")

# Save Boosted GLM results as new row in the result table
ecsta_results <- ecsta_results %>%
  add_row(Model = "Boosted GLM",
          Sensitivity = confmat_ecsta_glm$byClass["Sensitivity"],
          Specificity = confmat_ecsta_glm$byClass["Specificity"],
          Accuracy = confmat_ecsta_glm$overall["Accuracy"],
          Balanced.Accuracy = confmat_ecsta_glm$byClass["Balanced Accuracy"],
          Evaluation.Method = "10-fold CV")

# Set seed to 2021 for training the kNN model
set.seed(2021, sample.kind = "Rounding")
# Train kNN model for binary classification of users and non-users of
# Ecstasy using ten input features (see report) and 10-fold CV
ecsta_knn <- train(Ecstasy_User ~ Age + Gender + Education + NScore + EScore + 
                   OScore + AScore + CScore + Impulsiveness + SensationSeeking, 
                   data = data_clean, method = "knn", trControl = cv_10)
# Save confusion matrix of final model classification and actual class
confmat_ecsta_knn <- confusionMatrix(ecsta_knn$pred$pred,
                                     ecsta_knn$pred$obs,
                                     positive = "yes")

# Save kNN results as new row in the result table
ecsta_results <- ecsta_results %>%
  add_row(Model = "kNN",
          Sensitivity = confmat_ecsta_knn$byClass["Sensitivity"],
          Specificity = confmat_ecsta_knn$byClass["Specificity"],
          Accuracy = confmat_ecsta_knn$overall["Accuracy"],
          Balanced.Accuracy = confmat_ecsta_knn$byClass["Balanced Accuracy"],
          Evaluation.Method = "10-fold CV")

# Set seed to 2021 for training the Random Forest model
set.seed(2021, sample.kind = "Rounding")
# Train Random Forest model for binary classification of users and non-users of
# Ecstasy using ten input features (see report) and 10-fold CV
ecsta_rf <- train(Ecstasy_User ~ Age + Gender + Education + NScore + EScore + 
                    OScore + AScore + CScore + Impulsiveness + SensationSeeking,
                  data = data_clean, method = "rf", trControl = cv_10)
# Save confusion matrix of final model classification and actual class
confmat_ecsta_rf <- confusionMatrix(ecsta_rf$pred$pred,
                                    ecsta_rf$pred$obs,
                                    positive = "yes")

# Save Random Forest results as new row in the result table
ecsta_results <- ecsta_results %>%
  add_row(Model = "Random Forest",
          Sensitivity = confmat_ecsta_rf$byClass["Sensitivity"],
          Specificity = confmat_ecsta_rf$byClass["Specificity"],
          Accuracy = confmat_ecsta_rf$overall["Accuracy"],
          Balanced.Accuracy = confmat_ecsta_rf$byClass["Balanced Accuracy"],
          Evaluation.Method = "10-fold CV")

# Set seed to 2021 for training the RDA model
set.seed(2021, sample.kind = "Rounding")
# Train RDA model for binary classification of users and non-users of
# Ecstasy using ten input features (see report) and 10-fold CV
ecsta_rda <- train(Ecstasy_User ~ Age + Gender + Education + NScore + EScore + 
                   OScore + AScore + CScore + Impulsiveness + SensationSeeking, 
                   data = data_clean, method = "rda", trControl = cv_10)
# Save confusion matrix of final model classification and actual class
confmat_ecsta_rda <- confusionMatrix(ecsta_rda$pred$pred,
                                     ecsta_rda$pred$obs,
                                     positive = "yes")

# Save RDA results as new row in the result table
ecsta_results <- ecsta_results %>%
  add_row(Model = "RDA",
          Sensitivity = confmat_ecsta_rda$byClass["Sensitivity"],
          Specificity = confmat_ecsta_rda$byClass["Specificity"],
          Accuracy = confmat_ecsta_rda$overall["Accuracy"],
          Balanced.Accuracy = confmat_ecsta_rda$byClass["Balanced Accuracy"],
          Evaluation.Method = "10-fold CV")

# Save Ecstasy decision tree results of Mahyoub et al. 2019 for 
# comparison as new row in the result table
ecsta_results <- ecsta_results %>%
  add_row(Model = "Mahyoub et al. DT",
          Sensitivity = 0.532,
          Specificity = 0.653, 
          Accuracy = 0.6445,
          Balanced.Accuracy = 0.5925,
          Evaluation.Method = "10-fold CV")

# Save Ecstasy kNN results of Mahyoub et al. 2019 for 
# comparison as new row in the result table
ecsta_results <- ecsta_results %>%
  add_row(Model = "Mahyoub et al. kNN",
          Sensitivity = 0.589,
          Specificity = 0.765, 
          Accuracy = 0.7034,
          Balanced.Accuracy = 0.677,
          Evaluation.Method = "10-fold CV")

# Save Ecstasy Random Forest results of Mahyoub et al. 2019 for 
# comparison as new row in the result table
ecsta_results <- ecsta_results %>%
  add_row(Model = "Mahyoub et al. RF",
          Sensitivity = 0.594,
          Specificity = 0.711, 
          Accuracy = 0.7092,
          Balanced.Accuracy = 0.6525,
          Evaluation.Method = "10-fold CV")

# Save Ecstasy decision tree results of Fehrman et al. 2015 for
# comparison as new row in the result table
ecsta_results <- ecsta_results %>%
  add_row(Model = "Fehrman et al. DT",
          Sensitivity = 0.7617,
          Specificity = 0.7716, 
          Accuracy = NA,
          Balanced.Accuracy = 0.7667,
          Evaluation.Method = "LOOCV")

# Render result table for Ecstasy to the console
knitr::kable(ecsta_results)

################################################################################
#                                                                              #
# DRUG CORRELATION EXPERIMENT                                                  #
#                                                                              #
# In this experiment, we select the top-2 correlated drugs per evaluated       #
# drug and use the user/non-user assignment of the correlated drugs as         #
# additional input features. Thus, we can measure the impact on the            #
# performance if we would know whether the individual to be classified is a    #
# user or non-user of a correlated drug.                                       #
#                                                                              #
################################################################################

# Plot drug user group correlation
corrplot(cor(users_data))

# Create data frame of drug user group correlation
user_correlation <- as.data.frame(cor(users_data))

# Select top-3 correlated drugs for Benzodiazepines
user_correlation %>%
  dplyr::select(Benzos_User) %>%
  arrange(desc(Benzos_User)) %>%
  top_n(3)

# -> Top-2 correlated drugs excluding self-correlation for Benzodiazepines:
# Amphetamine_User + Meth_User

# Select top-3 correlated drugs for Legal Highs
user_correlation %>%
  dplyr::select(LegalHighs_User) %>%
  arrange(desc(LegalHighs_User)) %>%
  top_n(3)

# -> Top-2 correlated drugs excluding self-correlation for Legal Highs: 
# Ecstasy_User + MMushroom_User

# Select top-3 correlated drugs for Ecstasy
user_correlation %>%
  dplyr::select(Ecstasy_User) %>%
  arrange(desc(Ecstasy_User)) %>%
  top_n(3)

# -> Top-2 correlated drugs excluding self-correlation for Ecstasy: 
# Cocaine_User + MMushroom_User

################################################################################
#                                                                              #
# BENZODIAZEPINES WITH USER INFORMATION                                        #
#                                                                              #
# We now train an RDA model using Amphetamine_User and Meth_User as additional #
# input features. Afterwards, we compare the performance to the regular RDA    #
# model and the best comparison result of Fehrman et al 2015.                  #
#                                                                              #
################################################################################

# Create a data frame for storing the experimental Benzodiazepine results of the
# four evaluation metrics (see report). This data frame will later be rendered
# as a table.
benzo_results2 <- data.frame("Model" = character(),
                             "Sensitivity" = double(),
                             "Specificity" = double(),
                             "Accuracy" = double(), 
                             "Balanced Accuracy" = double(),
                             "Evaluation Method" = character())

# Save regular Benzodiazepine RDA model results for comparison as new row in
# the result table
benzo_results2 <- benzo_results2 %>%
  add_row(Model = "RDA",
          Sensitivity = confmat_benzo_rda$byClass["Sensitivity"],
          Specificity = confmat_benzo_rda$byClass["Specificity"],
          Accuracy = confmat_benzo_rda$overall["Accuracy"],
          Balanced.Accuracy = confmat_benzo_rda$byClass["Balanced Accuracy"],
          Evaluation.Method = "10-fold CV")

# Set seed to 2021 for training the experimental RDA model
set.seed(2021, sample.kind = "Rounding")
# Train experimental RDA model for binary classification of users and non-users
# of Bezodiazepines using ten input features + two correlated drug features 
# (see report) and 10-fold CV
benzo_rda2 <- train(Benzos_User ~ Age + Gender + Education + NScore + EScore + 
                      OScore + AScore + CScore + Impulsiveness + SensationSeeking +
                      Amphetamine_User + Meth_User, data = data_clean, 
                    method = "rda", trControl = cv_10)
# Save confusion matrix of final model classification and actual class
confmat_benzo_rda2 <- confusionMatrix(benzo_rda2$pred$pred,
                                      benzo_rda2$pred$obs,
                                      positive = "yes")

# Save results of new RDA model as new row in the result table
benzo_results2 <- benzo_results2 %>%
  add_row(Model = "RDA with user info",
          Sensitivity = confmat_benzo_rda2$byClass["Sensitivity"],
          Specificity = confmat_benzo_rda2$byClass["Specificity"],
          Accuracy = confmat_benzo_rda2$overall["Accuracy"],
          Balanced.Accuracy = confmat_benzo_rda2$byClass["Balanced Accuracy"],
          Evaluation.Method = "10-fold CV")

# Save Benzodiazepine decision tree results of Fehrman et al. 2015 for
# comparison as new row in the result table
benzo_results2 <- benzo_results2 %>%
  add_row(Model = "Fehrman et al. DT",
          Sensitivity = 0.7087,
          Specificity = 0.7151,
          Accuracy = NA,
          Balanced.Accuracy = 0.7119,
          Evaluation.Method = "LOOCV")

# Render experimental result table for Benzodiazepines to the console
knitr::kable(benzo_results2, digits = 3)

################################################################################
#                                                                              #
# LEGAL HIGHS WITH USER INFORMATION                                            #
#                                                                              #
# We now train an RDA model using Ecstasy_User and MMushroom_User as           #
# additional input features. Afterwards, we compare the performance to the     #
# regular RDA model and the best comparison result of Fehrman et al 2015.      #
#                                                                              #
################################################################################

# Create a data frame for storing the experimental Legal Highs results of the
# four evaluation metrics (see report). This data frame will later be rendered
# as a table.
lhigh_results2 <- data.frame("Model" = character(),
                             "Sensitivity" = double(),
                             "Specificity" = double(),
                             "Accuracy" = double(), 
                             "Balanced Accuracy" = double(),
                             "Evaluation Method" = character())

# Save regular Legal Highs RDA model results for comparison as new row in
# the result table
lhigh_results2 <- lhigh_results2 %>%
  add_row(Model = "RDA",
          Sensitivity = confmat_lh_rda$byClass["Sensitivity"],
          Specificity = confmat_lh_rda$byClass["Specificity"], 
          Accuracy = confmat_lh_rda$overall["Accuracy"],
          Balanced.Accuracy = confmat_lh_rda$byClass["Balanced Accuracy"],
          Evaluation.Method = "10-fold CV")

# Set seed to 2021 for training the experimental RDA model
set.seed(2021, sample.kind = "Rounding")
# Train experimental RDA model for binary classification of users and non-users
# of Legal Highs using ten input features + two correlated drug features 
# (see report) and 10-fold CV
lhigh_rda2 <- train(LegalHighs_User ~ Age + Gender + Education + NScore + EScore + 
                      OScore + AScore + CScore + Impulsiveness + SensationSeeking +
                      Ecstasy_User + MMushrooms_User, data = data_clean, 
                    method = "rda", trControl = cv_10)
# Save confusion matrix of final model classification and actual class
confmat_lh_rda2 <- confusionMatrix(lhigh_rda2$pred$pred,
                                   lhigh_rda2$pred$obs,
                                   positive = "yes")

# Save results of new RDA model as new row in the result table
lhigh_results2 <- lhigh_results2 %>%
  add_row(Model = "RDA with user info",
          Sensitivity = confmat_lh_rda2$byClass["Sensitivity"],
          Specificity = confmat_lh_rda2$byClass["Specificity"], 
          Accuracy = confmat_lh_rda2$overall["Accuracy"],
          Balanced.Accuracy = confmat_lh_rda2$byClass["Balanced Accuracy"],
          Evaluation.Method = "10-fold CV")

# Save Legal Highs decision tree results of Fehrman et al. 2015 for
# comparison as new row in the result table
lhigh_results2 <- lhigh_results2 %>%
  add_row(Model = "Fehrman et al. DT",
          Sensitivity = 0.7953,
          Specificity = 0.8237, 
          Accuracy = NA,
          Balanced.Accuracy = 0.8095,
          Evaluation.Method = "LOOCV")

# Render experimental result table for Legal Highs to the console
knitr::kable(lhigh_results2, digits = 3)

################################################################################
#                                                                              #
# ECSTASY MODEL WITH USER INFORMATION                                          #
#                                                                              #
# We now train an RDA model using Cocaine_User and MMushroom_User as           #
# additional input features. Afterwards, we compare the performance to the     #
# regular RDA model and the best comparison result of Fehrman et al 2015.      #
#                                                                              #
################################################################################

# Create a data frame for storing the experimental Ecstasy results of the
# four evaluation metrics (see report). This data frame will later be rendered
# as a table.
ecsta_results2 <- data.frame("Model" = character(),
                             "Sensitivity" = double(),
                             "Specificity" = double(),
                             "Accuracy" = double(), 
                             "Balanced Accuracy" = double(),
                             "Evaluation Method" = character())

# Save regular Ecstasy RDA model results for comparison as new row in
# the result table
ecsta_results2 <- ecsta_results2 %>%
  add_row(Model = "RDA",
          Sensitivity = confmat_ecsta_rda$byClass["Sensitivity"],
          Specificity = confmat_ecsta_rda$byClass["Specificity"],
          Accuracy = confmat_ecsta_rda$overall["Accuracy"],
          Balanced.Accuracy = confmat_ecsta_rda$byClass["Balanced Accuracy"],
          Evaluation.Method = "10-fold CV")

# Set seed to 2021 for training the experimental RDA model
set.seed(2021, sample.kind = "Rounding")
# Train experimental RDA model for binary classification of users and non-users
# of Ecstasy using ten input features + two correlated drug features 
# (see report) and 10-fold CV
ecsta_rda2 <- train(Ecstasy_User ~ Age + Gender + Education + NScore + EScore + 
                      OScore + AScore + CScore + Impulsiveness + SensationSeeking +
                      Cocaine_User + MMushrooms_User, data = data_clean, 
                    method = "rda", trControl = cv_10)
# Save confusion matrix of final model classification and actual class
confmat_ecsta_rda2 <- confusionMatrix(ecsta_rda2$pred$pred,
                                      ecsta_rda2$pred$obs,
                                      positive = "yes")

# Save results of new RDA model as new row in the result table
ecsta_results2 <- ecsta_results2 %>%
  add_row(Model = "RDA with user info",
          Sensitivity = confmat_ecsta_rda2$byClass["Sensitivity"],
          Specificity = confmat_ecsta_rda2$byClass["Specificity"],
          Accuracy = confmat_ecsta_rda2$overall["Accuracy"],
          Balanced.Accuracy = confmat_ecsta_rda2$byClass["Balanced Accuracy"],
          Evaluation.Method = "10-fold CV")

# Save Ecstasy decision tree results of Fehrman et al. 2015 for
# comparison as new row in the result table
ecsta_results2 <- ecsta_results2 %>%
  add_row(Model = "Fehrman et al. DT",
          Sensitivity = 0.7617,
          Specificity = 0.7716, 
          Accuracy = NA,
          Balanced.Accuracy = 0.7667,
          Evaluation.Method = "LOOCV")

# Render experimental result table for Ecstasy to the console
knitr::kable(ecsta_results2, digits = 3)
